import './globals.css'
import {ChakraProvider} from "@chakra-ui/react";
import React from "react";
import {ProviderWrapper} from "../../component/ProviderWrapper";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body>
    <ProviderWrapper>
      {children}
    </ProviderWrapper>
    </body>
    </html>
  )
}
